# Generated by Django 3.2.10 on 2024-12-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('planet', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('significance', models.TextField()),
            ],
            options={
                'db_table': 'planet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50, null=True)),
                ('mobile_no', models.CharField(max_length=15, null=True)),
                ('birth_date', models.DateField()),
                ('birth_time', models.TimeField()),
                ('birth_place', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='customerdetails',
            index=models.Index(fields=['mobile_no'], name='api_custome_mobile__13db5d_idx'),
        ),
        migrations.AddIndex(
            model_name='customerdetails',
            index=models.Index(fields=['email'], name='api_custome_email_af7e3d_idx'),
        ),
        migrations.AddIndex(
            model_name='customerdetails',
            index=models.Index(fields=['name'], name='api_custome_name_2e3788_idx'),
        ),
    ]
